```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Package changes for censored regression models

These are notes from a session where we discussed the required changes to tidymodels. Some open issues are:

* Where does the user specify the time points for certain performance metrics (e.g. ROC methods)? There could be an option to the `tune` functions (or their respective control functions) for this. Alternatively, `.time` could be encoded into a metric set. In either case, the `.time` vector will be passed to the `parsnip` predict calls (when appropriate) so that the right predictions are created. We will _not_ have a `.time` argument to `yardstick` metrics since the times will be in the results of the prediction functions. 

* `tune` has some functions that require the user to pick a metric. For example, `tune_bayes()` will optimize on the first metric in the metric set. Functions like `select_best()` or `autoplot()` have specific arguments for 1+ metrics. It is unclear how the use should pick a metric when some of them are computed at specific times. 

* There was some discussion about packages like `workflows` (and maybe `recipes`) making the time/event columns into a `Surv` object. This would simplify the changes to `tune` and other packages but increase the complexity to `workflows`. 

* The possibility of adding a subclass to `model_fit` objects for these types of models. 

Details on changes, per package, follow. 

## parsnip

* [x] Allow a new mode of  `"censored regression"`
* [x] Allow a new prediction types for linear predictors, time, survival probabilities, and hazard probabilities. 
* [ ] Restrict `fit_xy()` from working with censored regression models.
* [x] Document that the linear predictor prediction type will always be increasing with time. 
* [ ] Add linear predictor prediction types for existing parametric models (e.g. `glm` and so on)
* [ ] Add internal functions to enable censored regression models to make all types of predictions (e.g. time or probability based). 
* [ ] Add more models (on-going in the `censored` package). 

## rsample

* [ ] Prevent the user from passing `Surv` objects to the `strata` argument (or just extract the times when they do).

## yardstick

* [ ] Add new metric types for those that use censored regression probabilities (that require a time specification) and event time metrics (which are not dynamic).
* [ ] Add new metrics
* [ ] Determine how to create a metric set when the same metric is used with multiple times. 

## workflows

* [ ] Enable the workflow selector methods to accept the event type column as input.

## tune

* [ ] Add an approach for `autoplot()` to show probability-based metrics over time.
* [ ] Consider cases where `.time` contains a large number of time points. 
* [ ] Determine how to select a metric in functions like `select_best()` when the same metric is used over multiple time periods. 
* [ ] Update the logic to match prediction types to metric types. 

## recipes

* [ ] Document a standed role type for censoring indicator columns. 
* [ ] Create `step_surv()` to create `Surv` objects.
